# Generated by Django 4.2 on 2024-11-08 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rue', models.CharField(max_length=255)),
                ('n_rue', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'Adresse',
            },
        ),
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Editeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('isbn13', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('genre_litteraire', models.CharField(max_length=100)),
                ('sous_genre', models.CharField(max_length=100)),
                ('illustrateur', models.CharField(blank=True, max_length=100, null=True)),
                ('langue', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=50)),
                ('nombre_pages', models.IntegerField()),
                ('dimensions', models.CharField(max_length=50)),
                ('date_parution', models.DateField()),
                ('localisation', models.CharField(max_length=100)),
                ('synopsis', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url_reference', models.URLField(blank=True, null=True)),
                ('traducteur', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite_disponible', models.IntegerField()),
                ('quantite_totale', models.IntegerField()),
                ('quantite_minimale', models.IntegerField()),
                ('editeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.editeur')),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('pays', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Ville',
            },
        ),
        migrations.CreateModel(
            name='Reserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('statut', models.CharField(max_length=50)),
                ('date_reservation', models.DateField()),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.livre')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.personne')),
            ],
        ),
        migrations.AddField(
            model_name='personne',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.role'),
        ),
        migrations.CreateModel(
            name='Notifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('commentaire', models.TextField()),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.livre')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Ecrire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.auteur')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.livre')),
            ],
        ),
        migrations.CreateModel(
            name='Commander',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField()),
                ('quantite', models.IntegerField()),
                ('statut', models.CharField(max_length=50)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.livre')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.personne')),
            ],
        ),
        migrations.AddField(
            model_name='adresse',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.ville'),
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('date_achat', models.DateField()),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.livre')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.personne')),
            ],
        ),
    ]
