# Generated by Django 4.2.16 on 2024-11-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='date_parution',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='dimensions',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='format',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='genre_litteraire',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='langue',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='localisation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='nombre_pages',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='sous_genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='synopsis',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
