# Generated by Django 4.2 on 2024-12-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fournisseuradresse',
            table=None,
        ),
    ]
