# Generated by Django 4.2 on 2024-11-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='n_rue',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='achat',
            table='Achat',
        ),
        migrations.AlterModelTable(
            name='auteur',
            table='Auteur',
        ),
        migrations.AlterModelTable(
            name='commander',
            table='Commander',
        ),
        migrations.AlterModelTable(
            name='ecrire',
            table='Ecrire',
        ),
        migrations.AlterModelTable(
            name='editeur',
            table='Editeur',
        ),
        migrations.AlterModelTable(
            name='fournisseur',
            table='Fournisseur',
        ),
        migrations.AlterModelTable(
            name='livre',
            table='Livre',
        ),
        migrations.AlterModelTable(
            name='notifier',
            table='Notifier',
        ),
        migrations.AlterModelTable(
            name='personne',
            table='Personne',
        ),
        migrations.AlterModelTable(
            name='reserver',
            table='Reserver',
        ),
    ]
