# Generated by Django 4.2 on 2024-11-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_remove_personne_mot_de_passe_personne_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personne',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personne',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
