# Generated by Django 5.1.3 on 2024-11-17 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_rename_nom_fournisseur_nom_fournisseur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commander',
            name='fournisseur',
        ),
    ]
