# Generated by Django 4.2.16 on 2024-11-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_alter_livre_date_parution_alter_livre_dimensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
