# Generated by Django 4.2 on 2024-12-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0004_contributeur_remove_ecrire_auteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='contributeurs',
            field=models.ManyToManyField(blank=True, null=True, to='gui.contributeur'),
        ),
    ]
