# Generated by Django 4.2 on 2024-12-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0005_alter_livre_contributeurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='contributeurs',
            field=models.ManyToManyField(to='gui.contributeur'),
        ),
    ]
