# Generated by Django 4.2 on 2024-11-22 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0005_commander_fournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commander',
            name='date_commande',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='commander',
            name='statut',
            field=models.CharField(choices=[('en cours', 'En cours'), ('terminé', 'Terminé')], default='en cours', max_length=50),
        ),
        migrations.AlterField(
            model_name='reserver',
            name='date_reservation',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='reserver',
            name='quantite',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reserver',
            name='statut',
            field=models.CharField(choices=[('en cours', 'En cours'), ('terminé', 'Terminé')], default='en cours', max_length=50),
        ),
    ]
