# Generated by Django 4.2 on 2024-11-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0005_alter_ecrire_livre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ville',
            old_name='nom',
            new_name='nom_ville',
        ),
    ]
