# Generated by Django 4.2 on 2024-11-22 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0006_alter_commander_date_commande_alter_commander_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='adresse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.adresse'),
        ),
    ]
