# Generated by Django 4.2 on 2024-11-12 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0006_rename_nom_ville_nom_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editeur',
            name='id',
        ),
        migrations.AddField(
            model_name='notifier',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notifier',
            name='termine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='editeur',
            name='nom',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
