# Generated by Django 4.2 on 2024-11-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0007_fournisseur_adresse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='id',
        ),
        migrations.AlterField(
            model_name='personne',
            name='email',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
